### ISSUE TITLE
TJFF

### ISSUE THREAD

**Issue by AntiMoron** [QAQMiao/json#1]
# The Json File Format
===
Here is an introduction of json to QAQMiao and maybe other user searching documents of json file format.

**Comment by AntiMoron** [comment]
>first of all,I'd like to advise my lover QAQMiao to read this page : http://www.w3school.com.cn/json/json_syntax.asp
> It's an simple introduce from w3cschool which is a greenhand-friendly tutorial website of various technologies
> Also this page is in Chinese .I'm very sure that you would understand it easily.

**Comment by AntiMoron** [comment]
## Here is an abstraction of TJFF.
===
- Json is a file format forming as "key" : "value". This is like a map.In C++ it's ```std::map mp;mp[key]=value;```
- Json data is saved inside braces.For example
```json
{
      "key" : 123
}
```
- Json data is divided by commas.For example:
```json
{
    "key1" : 123,
    "key2" : "memeda"
}
```
## TJFF's data types.
For keys: It's basically like C.
For values:
|data type|details|
|numeric literal|e.g. 1   2.2  1.0|
|string literal|e.g. "memeda"|
|object|is included in braces.|
|array|is included in square brackets and divided by commas,for each element in the array,it's type can be numeric literal,string literal,object,and array.|
===

**Comment by AntiMoron** [comment]
## Let's look at somthing "Really(?)" complex.

```json
{
     "name" : "GaoBoyuan",
     "age" : 19,
     "sex" : "male",
     "handsome" : true,
     "girlfirend" : {
              "name" : "miaomiao",
              "sex" : "female",
              "age" : 20,
              "beautiful" : true
              "hobby" : ["tv operas","movies","pc games","computer science","Roller skating","cou re nao"]
      },
      "hobby" : ["pc games","computer science","music"]
}
```


Well, In this sample,you can easily get the information of GaoBoyuan & his girlfriend.

**Comment by QAQMiao** [comment]
我才不是你附属属性，嘤嘤嘤

**Comment by AntiMoron** [comment]
你就是好吧。。

**Comment by QAQMiao** [comment]
你欺负银。。。【躲墙角哭】

**Comment by AntiMoron** [comment]
追墙角亲你去！
