### ISSUE TITLE
Part 2.  WTD detail list.

### ISSUE THREAD

**Issue by AntiMoron** [QAQMiao/json#2]
### WTD is short of ```What to do```.
Here is a detail list of WTD.
In case of my babe getting tired of reading English.The context below will be written in Chinese.
现在我将写出一个列表来方便任务的进度跟踪，给自己做一个更好的规划。
应该遵循如下几种规矩|思想。
- 避免书写重复代码。举例如下：某个汽车销售中心需要小喵编写程序来进行汽车的信息管理。现在已知有3道流程需要获取到汽车的信息，三个流程分别是pass1,pass2,pass3。并且有一个1万左右的销售量，他们已经被存储在一个vector里了。
```c++
struct cars{...};
std::vector<cars> datas;
...
//在这里的时候假定datas里面已经包含了上万条汽车的记录。中间发生了什么我们不关注
//此时执行pass1
for(int i=0;i<datas.size();i++)
{
    ...
}
//此时执行pass2
for(int i=0;i<datas.size();i++)
{
    ...
}
//此时执行pass3
for(int i=0;i<datas.size();i++)
{
     ...
}
```
后来啊，这个汽车销售中心因为一批车辆有问题被召回了，只有索引为第1000号以后的车辆才需要经过这三个流程，而那些被召回车辆的数据也不能删除，以防日后需要对其数据进行查询。因此小喵需要这样子改代码：
```c++
//此时执行pass1
for(int i=1000;i<datas.size();i++)
{
    ...
}
//此时执行pass2
for(int i=1000;i<datas.size();i++)
{
    ...
}
//此时执行pass3
for(int i=1000;i<datas.size();i++)
{
     ...
}
```

尼玛的坑爹呢这是啊！？？！？？
”还好没有1000个流程，不然我岂不是要改1000处。而且我这样做很容易出错的啊，万一哪一天我睡多了迷迷糊糊少改了一个怎么办！程序不就出bug了么！“ 小喵这样ji叫喊道。所以老狗过来和小喵说：你应该把你的代码这样子改：
```c++
int startIndex = 1000;
int endIndex = datas.size();
//此时执行pass1
for(int i=startIndex ;i<endIndex ;i++)
{
    ...
}
//此时执行pass2
for(int i=startIndex ;i<endIndex ;i++)
{
    ...
}
//此时执行pass3
for(int i=startIndex ;i<endIndex ;i++)
{
     ...
}
```
"这样子开始位置和结束位置只要改startIndex和endIndex这两处就OK了，而且以后需求有变更的话也很容易修改哈！？"老狗这样和小喵说。
这就是传说中的OOP(Object Oriented Programming)的基本思想之一。

**Comment by AntiMoron** [comment]
- 尽量将工程模块划分得较细，不过细化程度要合理。
看以下案例：
小喵应老板要求用c++解析json的文件格式。
写出了下面的代码：
```c++
void JsonParse()
{
    FILE* fp = fopen("spec.json","r");
    //文件内容，通过循环将文件包含的字符串获取到fileContext里面
    std::string fileContext;
    while(feof(fp))
    {
           fileContext += fgetc(fp);
    }
    //下面是针对fileContext的字符串操作，具体操作流程不关心。
    ...
    fclose(fp);
}
```
后来老板又让她解析更多的文件格式，如xml ,于是勤奋的小喵又开始去写：
```c++
void XmlParse()
{
    FILE* fp = fopen("spec.xml","r");
    //文件内容，通过循环将文件包含的字符串获取到fileContext里面
    std::string fileContext;
    while(feof(fp))
    {
           fileContext += fgetc(fp);
    }
    //下面是针对字符串fileContext的文件内容的解析
    ...
    fclose(fp);
}
```

"8-( 哦草，有重复代码了。。要是再给我几十种文件格式我整个人都要因为这几行崩溃了，操作文件可是很容易有遗漏过失的地方啊。"小喵看着老狗尖叫着说。。

老狗：”该！谁让你不分模块的，我要是你，我就会这样写：“
```
std::string getFileContext(const char* fileName)
{
      std::string fileContext;
      FILE* fp = fopen(fileName,"r");
      while(feof(fp))
      {
              fileContext += fgetc(fp);
      }
      fclose(fp);
      return fileContext;
}

void parseXml()
{
       std::string  fileContext = getFileContext("spec.xml");
       //针对文件内容的字符串的处理操作
       ...
}

void parseJson()
{
        std::string fileContext = getFileContext("spec.json");
       //针对文件内容的字符串的处理操作
        ...
}
```

”这样子就算再来10个文件格式，起码文件内容的读取这边我也能用这样一行代码来快速写出来，还不会出错“ 老狗胸有成竹道。

**Comment by AntiMoron** [comment]
严格遵守以上的规则之后，对于书写规范也要有要求，对于新手，不需要太详细的规范。
### 我简单介绍下我比较喜欢的书写方式：
>大驼峰：
>就是所有的单词首字母大写： ```SlimShady```,```SlamDunk```,```FunctionallyFuckMe```.
>小驼峰：
>就是除了第一个单词之外的首字母大写： ```slimShady```,```slamDunk```, ```functionallyFuckMe```.

知道以上两种命名风格就够了：
所以针对类名，我选用大驼峰： ```class FileReader; class DataFetcher;```
针对函数名，我选用小驼峰： ```void addChild(); void delChild();```
针对宏，常量，我用全大写： ```#define MIAOMIAO ”my babe“```, ```const int VALUE = 123;```
这样的命名比较好看而且有规律可循，意义也很明朗地表现出来，```尽量避免无意义的命名！！！```

### 排版
对于双目运算符号，前后要有空格，对于++,--这样的单目运算符，就不用前后空格了。
对于大括号，需要单独站一行(lambda除外，新手未接触lambda的忽略本括号内容)。
对于tab键，按出来要是4个空格宽。最好不要用空格，而是单独用tab字符。比较好改而已，我的习惯。
小朋友们欢呼雀跃吧，剩下的部分基本没什么严格要求！大致看起来这个样子就好了。
```c++
for(int i = 0;i < 10;i++)
{
     for(int j = 10; j < 100;j++)
     {
            int k = 100;
            k = k + 10;
            --k;
            k++;
            k ^= 0xffff;
     }
}
```

**Comment by AntiMoron** [comment]
P.S. 添加一条补充的遵守的规则。参考gulp plugin的tutorial。
- do things simply & do things correctly.

**Comment by AntiMoron** [comment]
P.S. 补充一个代码书写规则。每个文件最后要有单独的一行空行。

**Comment by QAQMiao** [comment]
Thank you very much for the thing I have forgotten.
Goodbye , memory.
